apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: aigc
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        args: ["--ak", "${QWEN_API_KEY}"]
        ports:
        - containerPort: 7860
        resources:
            requests:
              cpu: "100m"
              memory: "32Mi"
            limits:
              cpu: "2"
              memory: "512Mi"
        livenessProbe: 
            tcpSocket:
              port: 7860
            initialDelaySeconds: 5
            periodSeconds: 5
        readinessProbe:
              tcpSocket:
                port: 7860
              initialDelaySeconds: 5
              periodSeconds: 5
      imagePullSecrets:
        - name: sg-acr-credential
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: aigc
spec:
  selector:
    app: ${APP_NAME}
  ports:
  - port: 7860
    targetPort: 7860
  type: ClusterIP
