# 使用官方 Ubuntu 作为基础镜像
FROM ubuntu:22.04

# 安装 Python3 和 pip3 及一些依赖工具
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    build-essential \
    git \
    curl \
    && apt-get clean

# 拷贝 requirements.txt 到容器中
COPY requirements.txt /app/requirements.txt

# 设置工作目录
WORKDIR /app

# 安装 Python 依赖
RUN pip3 install --upgrade pip \
    && pip3 install -r requirements.txt

# 默认命令
CMD [ "python3" ]

# docker build -t python-base-image:v1.0.1 .
# docker tag python-base-image:v1.0.1 registry.ap-southeast-1.aliyuncs.com/python-base-image:v1.0.1
# docker login registry.ap-southeast-1.aliyuncs.com
# docker push registry.ap-southeast-1.aliyuncs.com/python-base-image:v1.0.1
