FROM python:3.10.17-slim-bookworm

# 拷贝 requirements.txt 到容器中
COPY requirements.txt /app/requirements.txt

# 设置工作目录
WORKDIR /app

# 安装 Python 依赖
RUN pip3 install --upgrade pip \
&& pip3 install --no-cache-dir -r requirements.txt

# 默认命令
CMD [ "python3" ]

# docker build -f Dockerfile-base -t python-base-image:v1.0.1 
# docker tag python-base-image:v1.0.1 registry.ap-southeast-1.aliyuncs.com/dev-shengshi/python-base-image:v1.0.1
# docker login registry.ap-southeast-1.aliyuncs.com
# docker push registry.ap-southeast-1.aliyuncs.com/dev-shengshi/python-base-image:v1.0.1